
#PARA CONECTARSE A LA BASE DE DATOS H2
spring.datasource.url=jdbc:h2:file:./data/proveedores
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

#PARA CONECTARSE A LA BASE DE DATOS MYSQL
#spring.datasource.url=jdbc:mysql://localhost:3306/proyectoFinal
#spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=root
